location: .gitman
sources:
  - repo: https://github.com/VIS4ROB-lab/mrs_multirotor_simulator
    name: mrs_multirotor_simulator
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_multirotor_simulator
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_uav_state_estimators.git
    name: mrs_uav_state_estimators
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_uav_state_estimators
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_uav_hw_api.git
    name: mrs_uav_hw_api
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_uav_hw_api
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_lib.git
    name: mrs_lib
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_lib
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_msgs.git
    name: mrs_msgs
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_uav_autostart.git
    name: mrs_uav_autostart
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_uav_autostart
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_uav_trajectory_generation.git
    name: mrs_uav_trajectory_generation
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/VIS4ROB-lab/mrs_uav_status.git
    name: mrs_uav_status
    rev: humble
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_uav_status
    scripts:
      - git submodule update --init --recursive
